"""Built-in host bundles for the proxy's `[proxy] passthrough` allow-list.

These are the *trusted, expected* dev-toolchain hosts. Under `capture=on` the proxy TLS-PASSES
THROUGH them (real certs end-to-end, SNI/host-level log only — we already know what they are and
don't need request-level scrutiny) and MITM-DECRYPTS everything NOT listed (the surprising egress
worth inspecting). A project references them by `@bundle` in `foldyard.toml`
(``[proxy] passthrough = ["@anthropic", "@vcs", "my-api.internal"]``); `@all` = every bundle, and
is the default when the key is absent.

Seeded from Claude Code Web's "Trusted network access" default-allowed domains. Wildcard
semantics match: ``*.foo.com`` matches any SUBDOMAIN of foo.com (not foo.com itself) — list the
bare host too when you want both, exactly as the upstream list does.
"""

from __future__ import annotations

# Category → trusted hosts. Keep grouped (and roughly in the upstream's order) so it's easy to
# diff against Claude Code Web's published list when it changes.
BUNDLES: dict[str, tuple[str, ...]] = {
    "anthropic": (
        "api.anthropic.com",
        "statsig.anthropic.com",
        "docs.claude.com",
        "platform.claude.com",
        "code.claude.com",
        "claude.ai",
    ),
    "vcs": (
        "github.com",
        "www.github.com",
        "api.github.com",
        "npm.pkg.github.com",
        "raw.githubusercontent.com",
        "pkg-npm.githubusercontent.com",
        "objects.githubusercontent.com",
        "release-assets.githubusercontent.com",
        "codeload.github.com",
        "avatars.githubusercontent.com",
        "camo.githubusercontent.com",
        "gist.github.com",
        "gitlab.com",
        "www.gitlab.com",
        "registry.gitlab.com",
        "bitbucket.org",
        "www.bitbucket.org",
        "api.bitbucket.org",
    ),
    "containers": (
        "registry-1.docker.io",
        "auth.docker.io",
        "index.docker.io",
        "hub.docker.com",
        "www.docker.com",
        "production.cloudflare.docker.com",
        "download.docker.com",
        "gcr.io",
        "*.gcr.io",
        "ghcr.io",
        "mcr.microsoft.com",
        "*.data.mcr.microsoft.com",
        "public.ecr.aws",
    ),
    "cloud": (
        "cloud.google.com",
        "accounts.google.com",
        "gcloud.google.com",
        "*.googleapis.com",
        "storage.googleapis.com",
        "compute.googleapis.com",
        "container.googleapis.com",
        "azure.com",
        "portal.azure.com",
        "microsoft.com",
        "www.microsoft.com",
        "*.microsoftonline.com",
        "packages.microsoft.com",
        "dotnet.microsoft.com",
        "dot.net",
        "visualstudio.com",
        "dev.azure.com",
        "*.amazonaws.com",
        "*.api.aws",
        "oracle.com",
        "www.oracle.com",
        "java.com",
        "www.java.com",
        "java.net",
        "www.java.net",
        "download.oracle.com",
        "yum.oracle.com",
    ),
    "node": (
        "registry.npmjs.org",
        "www.npmjs.com",
        "www.npmjs.org",
        "npmjs.com",
        "npmjs.org",
        "yarnpkg.com",
        "registry.yarnpkg.com",
    ),
    "python": (
        "pypi.org",
        "www.pypi.org",
        "files.pythonhosted.org",
        "pythonhosted.org",
        "test.pypi.org",
        "pypi.python.org",
        "pypa.io",
        "www.pypa.io",
    ),
    "ruby": (
        "rubygems.org",
        "www.rubygems.org",
        "api.rubygems.org",
        "index.rubygems.org",
        "ruby-lang.org",
        "www.ruby-lang.org",
        "rubyforge.org",
        "www.rubyforge.org",
        "rubyonrails.org",
        "www.rubyonrails.org",
        "rvm.io",
        "get.rvm.io",
    ),
    "rust": (
        "crates.io",
        "www.crates.io",
        "index.crates.io",
        "static.crates.io",
        "rustup.rs",
        "static.rust-lang.org",
        "www.rust-lang.org",
    ),
    "go": (
        "proxy.golang.org",
        "sum.golang.org",
        "index.golang.org",
        "golang.org",
        "www.golang.org",
        "goproxy.io",
        "pkg.go.dev",
    ),
    "jvm": (
        "maven.org",
        "repo.maven.org",
        "central.maven.org",
        "repo1.maven.org",
        "repo.maven.apache.org",
        "jcenter.bintray.com",
        "gradle.org",
        "www.gradle.org",
        "services.gradle.org",
        "plugins.gradle.org",
        "kotlinlang.org",
        "www.kotlinlang.org",
        "spring.io",
        "repo.spring.io",
    ),
    "other-pkg": (
        "packagist.org",
        "www.packagist.org",
        "repo.packagist.org",
        "nuget.org",
        "www.nuget.org",
        "api.nuget.org",
        "pub.dev",
        "api.pub.dev",
        "hex.pm",
        "www.hex.pm",
        "cpan.org",
        "www.cpan.org",
        "metacpan.org",
        "www.metacpan.org",
        "api.metacpan.org",
        "cocoapods.org",
        "www.cocoapods.org",
        "cdn.cocoapods.org",
        "haskell.org",
        "www.haskell.org",
        "hackage.haskell.org",
        "swift.org",
        "www.swift.org",
    ),
    "linux": (
        "archive.ubuntu.com",
        "security.ubuntu.com",
        "ubuntu.com",
        "www.ubuntu.com",
        "*.ubuntu.com",
        "ppa.launchpad.net",
        "launchpad.net",
        "www.launchpad.net",
        "*.nixos.org",
    ),
    "devtools": (
        "dl.k8s.io",
        "pkgs.k8s.io",
        "k8s.io",
        "www.k8s.io",
        "releases.hashicorp.com",
        "apt.releases.hashicorp.com",
        "rpm.releases.hashicorp.com",
        "archive.releases.hashicorp.com",
        "hashicorp.com",
        "www.hashicorp.com",
        "repo.anaconda.com",
        "conda.anaconda.org",
        "anaconda.org",
        "www.anaconda.com",
        "anaconda.com",
        "continuum.io",
        "apache.org",
        "www.apache.org",
        "archive.apache.org",
        "downloads.apache.org",
        "eclipse.org",
        "www.eclipse.org",
        "download.eclipse.org",
        "nodejs.org",
        "www.nodejs.org",
        "developer.apple.com",
        "developer.android.com",
        "pkg.stainless.com",
        "binaries.prisma.sh",
    ),
    "monitoring": (
        "sentry.io",
        "*.sentry.io",
        "downloads.sentry-cdn.com",
    ),
    "cdn": (
        "sourceforge.net",
        "*.sourceforge.net",
        "packagecloud.io",
        "*.packagecloud.io",
        "fonts.googleapis.com",
        "fonts.gstatic.com",
    ),
    "schema": (
        "json-schema.org",
        "www.json-schema.org",
        "json.schemastore.org",
        "www.schemastore.org",
    ),
    "mcp": ("*.modelcontextprotocol.io",),
}
